# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mDC0LRb1KSAW7QT1uiDkRumv1WA7o9tG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv("/content/Zomato data .csv")
print(data.head())

def handleRate(value):
	value=str(value).split('/')
	value=value[0];
	return float(value)

data['rate']=data['rate'].apply(handleRate)
print(data.head())

data.info()

sns.countplot(x=data['listed_in(type)'])
plt.xlabel("Type of restaurant")

grouped_data = data.groupby('listed_in(type)')['votes'].sum()
result = pd.DataFrame({'votes': grouped_data})
plt.plot(result, c="green", marker="o")
plt.xlabel("Type of restaurant", c="red", size=20)
plt.ylabel("Votes", c="red", size=20)

max_votes = data['votes'].max()
restaurant_with_max_votes = data.loc[data['votes'] == max_votes, 'name']

print("Restaurant(s) with the maximum votes:")
print(restaurant_with_max_votes)

sns.countplot(x=data['online_order'])

plt.hist(data['rate'],bins=5)
plt.title("Ratings Distribution")
plt.show()

couple_data=data['approx_cost(for two people)']
sns.countplot(x=couple_data)

plt.figure(figsize = (6,6))
sns.boxplot(x = 'online_order', y = 'rate', data = data)

pivot_table = data.pivot_table(index='listed_in(type)', columns='online_order', aggfunc='size', fill_value=0)
sns.heatmap(pivot_table, annot=True, cmap="YlGnBu", fmt='d')
plt.title("Heatmap")
plt.xlabel("Online Order")
plt.ylabel("Listed In (Type)")
plt.show()

